# Generated by Django 6.0.5 on 2026-06-24 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_email_student_enrollment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата зачисления"
            ),
        ),
    ]
